# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PdfSplitter import PdfSplitter


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("PDF Splitter")
        Dialog.resize(501, 104)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 60, 341, 32))
        self.buttonBox.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Europe)
        )
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pdfFileName = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.pdfFileName.setObjectName("pdfFileName")
        self.horizontalLayout.addWidget(self.pdfFileName)
        self.loadFile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loadFile.setObjectName("loadFile")
        self.horizontalLayout.addWidget(self.loadFile)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("PDF Splitter", "PDF Splitter"))
        self.loadFile.setText(_translate("Dialog", "Load file"))

    # own functions
    def setupUi2(self, Dialog):
        self.loadFile.clicked.connect(self.selectFile)
        self.buttonBox.accepted.connect(self.splitFile)

    def selectFile(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()[0]
        self.pdfFileName.setText(filename)

    def splitFile(self):
        pdfSplitter = PdfSplitter()
        fileName = str(self.pdfFileName.text())
        print(fileName)
        pdfSplitter.split(fileName)

    # own functions end


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    ui.setupUi2(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
